#!/usr/bin/env python

import click
import requests


def status_code(url):
    response = requests.head(url)

    return response.status_code


@click.command()
@click.argument('url')
def main(url):
    status = status_code(url)
    print(f'{url} returned a {status} status.')


if __name__ == '__main__':
    main('https://www.google.com')